### ISSUE TITLE
it would be nice to have hint for "Library name"

### ISSUE THREAD

**Issue by stevermeister** [gonzofish/angular-librarian#31]
that could be taken from package.json

**Comment by gonzofish** [comment]
Not a bad idea. Would you be interested in doing a PR?

**Comment by stevermeister** [comment]
frankly speaking, I'm looking forward to see something official for library support, like angular-cli

btw, according to repo updates you found another tool?

**Comment by stevermeister** [comment]
I found this one - https://github.com/jvandemo/generator-angular2-library
but not big fan of yeoman, so may be there is even better one

**Comment by gonzofish** [comment]
> btw, according to repo updates you found another tool?

not sure what you mean.

As far as yeoman, I've always thought it was a bit bulky--which has made me shy from it

**Comment by gonzofish** [comment]
Closed by 20195b3

**Comment by stevermeister** [comment]
thx!

**Comment by gonzofish** [comment]
no problem--it might be a bit before it's added to a release, but not too long--I'm working towards a true version 1 right now
