### ISSUE TITLE
Improve Upgrade Experience

### ISSUE THREAD

**Issue by gonzofish** [gonzofish/angular-librarian#38]
When moving from one version of librarian to the next, the upgrade experience is a little off. The current strategy is using the `init` command, which makes the user go through the CLI inputs (like specifying the project name). This shouldn't need to be done so manually.

There are two ways we can accomplish this:

1. An `update` command which takes the previous `.erector` values and rescaffolds the project
2. A post-install step that does the same as the `update` command

I like 2, but, not being an NPM guru, I'm not 100% sure if it's viable.

**Comment by tommueller** [comment]
So it's me again. I tried upgrading another library (that actually has more code, so redoing everything would be more annoying.
I upgraded the librarian via npm and run `ngl i`, the wizard asks me for Library name, README title, Repository URL, everything is filled out with former values, so no biggie. *BUT* I cannot complete the upgrade. I cannot get past the _Reinitialize Git project?_, the question keeps flickering and I cannot enter anything. I think it gets reloaded somehow all the time.
After about one or two minutes I get this error:

```
Reinitialize Git project (y/N)? 
<--- Last few GCs --->

  144670 ms: Mark-sweep 1384.4 (1435.7) -> 1384.4 (1435.7) MB, 993.5 / 0.0 ms [allocation failure] [GC in old space requested].
  145647 ms: Mark-sweep 1384.4 (1435.7) -> 1384.4 (1435.7) MB, 977.1 / 0.0 ms [allocation failure] [GC in old space requested].
  146613 ms: Mark-sweep 1384.4 (1435.7) -> 1384.4 (1419.7) MB, 966.2 / 0.0 ms [last resort gc].
  147579 ms: Mark-sweep 1384.4 (1419.7) -> 1384.4 (1419.7) MB, 965.6 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3074e0dcfb39 <JS Object>
    1: nextTick [internal/process/next_tick.js:~140] [pc=0xf684f0ce866] (this=0x103e665972b1 <a process with map 0x2de14ac11619>,callback=0x1f2d8e01a879 <JS Function afterWrite (SharedFunctionInfo 0x103e66553859)>)
    2: arguments adaptor frame: 5->1
    3: onwrite(aka onwrite) [_stream_writable.js:~353] [pc=0xf684f0ae9c9] (this=0x3074e0d04381 <undefined>,stream=0x1f2d8e0c1769 <a WriteStream w...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x10d368c [node]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 7: 0xf684ef079a7
Aborted

npm ERR! Linux 4.8.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "g" "i"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! company-Core@0.1.1 g: `node ./node_modules/angular-librarian "i"`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the company-Core@0.1.1 g script 'node ./node_modules/angular-librarian "i"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the company-Core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/angular-librarian "i"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs company-Core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls company-Core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/workspace_angular/company-Core/npm-debug.log
```

**Comment by gonzofish** [comment]
Hmm. The debug log and stack trace aren't giving a good indication of what's going on, but if it is related to reinitializing Git, then the place this would be failing is on the removal of the `.git` directory.

The way we handle this is by basically going into the `.git` folder and recursively removing all files & folders from the bottom up. Again, if it is because of the reinit of Git, there might be some infinite recursion going on that's overloading the heap.

Again, this isn't something I've seen happen so it's tough to debug...could you remove `.git` manually and do `ngl i` again?

**Comment by tommueller** [comment]
Seems like the upgrade ran through despite the error, at least I can build the project with scss imports. Will check what happens after deleting _.git_-folder in a free second.

**Comment by gonzofish** [comment]
no problem. thanks again

**Comment by tommueller** [comment]
Same problem without .git folder!

**Comment by gonzofish** [comment]
Hmm. This is troubling...it doesn't make any sense to me, but I'll try to reproduce

**Comment by tommueller** [comment]
I will try to get a project up with this to reproduce, but it'll take me a while (not in office Thursdays and Fridays!)

**Comment by gonzofish** [comment]
No problem, you're helping me out--if you figure it out and want to contribute back, let me know. I can help you better understand the project

**Comment by tommueller** [comment]
Ok, I managed to reproduce this with the most simple case. These are the steps I performed:

### Reproduce not upgradeable project
- `mkdir librarian-test`
- `cd librarian-test`
- `npm init -f`
- `npm i -D angular-librarian@1.0.0-alpha.14`
- `ngl i`
  - enter following data:
     - repository url: https://github.com/tommueller/librarian-test 
     - reinit git: yes

__Project is running!__

- update version of angular-librarian to alpha 17 in package.json
- `npm upgrade`
- `ngl i `

gets stuck at git-reinit question and eventually crashes with js-heap out of memory

**Comment by gonzofish** [comment]
@tommueller you are awesome for figuring out how to get this to reproduce

let me investigate!

**Comment by gonzofish** [comment]
I think I may have figure out the culprit here--we store the answer to the git init question as a boolean, but the STDOUT wants a string and we're not giving it one. It tries to parse `true` as a string and that fails.

**Comment by gonzofish** [comment]
Interestingly enough, this is actual an issue with the scaffolding library [erector-set](https://github.com/gonzofish/erector-set) so I'm filing the issue against that library.

**Comment by gonzofish** [comment]
Update published to the upgrade issue here, version is 1.0.0-alpha.18

**Comment by tommueller** [comment]
Great, thanks for the quick fix!

**Comment by gonzofish** [comment]
Worked for me...let's hope it does for you too 😰

**Comment by tommueller** [comment]
Yep works for me as well! Thanks

Is it really necessary to run the whole command again though? Including `npm install` etc.?

**Comment by gonzofish** [comment]
That's what I'm trying to work out with this issue

**Comment by gonzofish** [comment]
Also it is necessary to run through NPM install if there's a change in the dependencies of `package.json`. But that doesn't have to happen _every_ time.

Most of the `init` process doesn't need to happen on an upgrade--only the updating of files angular-librarian provides (webpack files, karma.conf, etc.) and (occassionally) running `npm install`. 

If there isn't a significant change in any dependency version (ie, we haven't moved to Angular 5), there really isn't a need to do an `npm install`. However, we can allow the user to provide an option to `ngl update` that runs `npm install`, like `ngl u deps` or something

**Comment by gonzofish** [comment]
First off, the upgrade functionality is going to bring with it an auto-upgrade of angular-librarian. Meaning, after the first version of the update is out there, you'll be able to run `ngl upgrade` and angular-librarian will check for a new version. If one is out there, it will upgrade your application.

Secondly, the following files will be upgrade-able and will be 100% managed by angular-librarian:

1. `webpack/webpack.*.js` files
2. `karma.conf.js`
3. `tasks/*`
4. `tsconfig.*.json`
5. `tslint.json`

In order to allow flexibility to the developer using angular-librarian, we'll be offering extensibility to the Webpack files and `karma.conf.js`. To do, we'll add a `config` directory to root files can be added with conventions:

- To add functionality to Webpack files, place a `webpack.[config type].js` file in `configs`
    - The `module.exports` should be a JSON object or function
- To add karma functionality, add a `karma.conf.js` to `configs`
    - The `module.exports` should be a function that takes in the `config` object and returns a JSON object

The files under `tasks` should not be modified by the developer/user. And the any additions/modifications to the TypeScript JSON files will be handled by doing a deep merge of the new JSON and the existing one.

By doing all this we can overwrite files (diffing them is proving to be quite difficult) and allow customization by developers using angular-librarian. Basically we'll deem the files mentioned above as "can change on upgrade".

**Comment by gonzofish** [comment]
1. Get user configs working
    - ~~Webpack~~
    - Karma
2. Get TypeScript files updating properly

**Comment by gonzofish** [comment]
I'm not closing this yet--going to put it into a beta first

**Comment by gonzofish** [comment]
Working properly as of c11b095

**Comment by tommueller** [comment]
great, thanks!
