### ISSUE TITLE
Component gets exported but does not work when imported

### ISSUE THREAD

**Issue by tommueller** [gonzofish/angular-librarian#41]
Me one more time ... with the new version I created a module, which contains one single component. When I import this into my main-project it does not give any errors, so apparently the component is somehow found, but I does not show up.

Checking the DOM, the page loads the main element of the component
```
<collection _ngcontent-c20="" _nghost-c21="" ng-reflect-items="[Object object, Object object" ng-reflect-header="Custom-Title" class=""></collection>
```

So data gets loaded into it (items and header), but the element does not have any content. In my example folder within the library it works without any problems.

Did you have this problem before and can give me any hint on how to fix this?

**Comment by gonzofish** [comment]
Are you making sure the component is in the `exports` of your module? Also try making sure that the component is being exported in `src/index.ts`

I haven't had any issues with consuming components so far, so it's a bit tough to understand what the issue may be

**Comment by tommueller** [comment]
Yes it gets exported properly. I just found the problem (not the fix though): after building the project in the _collection.component.js_ the template is empty (the html doesn't get inserted):

```
CollectionComponent.decorators = [
    { type: Component, args: [{
                selector: 'collection',
                template: "",
                styles: [".collection { margin: 8px 0 8px 0; border: 1px solid rgba(0, 0, 0, 0.12); border-radius: 2px; overflow: hidden; position: relative; } "]
            },] },
];
```

**Comment by gonzofish** [comment]
can i see the componet's code?

**Comment by tommueller** [comment]
Using an inline-template solves this problem!

components code:
```
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'collection',
  template: './collection.component.html',
  styleUrls: ['./collection.component.scss']
})
export class CollectionComponent implements OnInit {

  @Input() items: Array<any>;
  @Input() header: string;
  @Output() selectedChange = new EventEmitter();

  selected: any;

  constructor() { }

  ngOnInit() { }

  select(item: any) {
    this.selected = item;
    this.selectedChange.emit(this.selected);
  }

}
```

Doesn't matter what _collection.component.html_ contains, did not get copied even with just
```
<h1>Test</h1>
```
as template ...

**Comment by gonzofish** [comment]
Interesting, that means that the inline script isn't doing it's job...can you copy your `tasks/inline-resources.js` file for me?

**Comment by gonzofish** [comment]
Actually, nevermind, I'm seeing the same thing here...shoot, something must've broke with that Sass fix--sorry I'll have it fixed ASAP

**Comment by gonzofish** [comment]
Oh, jeez. I made a big change and I can see what broke it. Thanks again for being vocal about your issues, it's making this project better for both of us!

**Comment by gonzofish** [comment]
Until I can get a fix published to NPM, you can do this manually:

1. Open `tasks/inline-resources.js`
2. Go to line 83-- you should be in the function `getMiniContents` and the line should just be the closing brace of an `if` statemtent
3. Paste the following right after that closing brace:
    ```javascript
    else {
        template = fs.readFileSync(file, 'utf8');
    }
    ```
What happened is that I stopped reading the Sass files manually, but in the process stopped reading HTML files as well, so they were not getting inlined. This should handle it now.

Let me know if it works

**Comment by tommueller** [comment]
Sorry, already out of office, can only comment on this on Monday.

Thanks for looking into it and fixing this so quickly!

**Comment by tommueller** [comment]
Just checked this and it does work! Thanks!

**Comment by gonzofish** [comment]
Great!

**Comment by gonzofish** [comment]
Whoops, haven't released the fix yet
