### ISSUE TITLE
P alias triggers publish instead of pipe

### ISSUE THREAD

**Issue by Itschrismorgan** [gonzofish/angular-librarian#45]
It looks like the ```p``` alias is defined twice for both publish and pipe.

I could create a PR to change the alias for publish to be ```pub``` and leave ```p``` for pipe.

That would keep pipe consistent with the aliases for component, service, and directive.

I would update the docs to match the change as well.

**Comment by gonzofish** [comment]
Absolutely! The file is located here: https://github.com/gonzofish/angular-librarian/blob/master/index.js if you didn't know that already

Thanks

**Comment by gonzofish** [comment]
Oh, and if you could update the README to match, that'd be awesome

**Comment by gonzofish** [comment]
Closed by #46 (talk about a quick turnaround!)
