### ISSUE TITLE
ng serve command is broken after installing package created by angular-librarian

### ISSUE THREAD

**Issue by stevermeister** [gonzofish/angular-librarian#51]
not sure whether it's a bug of angular-librarian, but decided to report it also here to let you know
https://github.com/angular/angular-cli/issues/6961

**Comment by gonzofish** [comment]
That's very strange--I'll try setting up a project myself and seeing what happens

**Comment by gonzofish** [comment]
it looks like the CLI changed how they're handling packages in 1.2 so I think what's happening is that installing a 3rd party package installs the `@angular/*` packages more than once as far as the CLI can tell

**Comment by gonzofish** [comment]
I ran `npm install` inside `myapp` and everything seemed to work after that

**Comment by stevermeister** [comment]
even after `npm install` does not work for me :(

**Comment by gonzofish** [comment]
you're getting the same error?

**Comment by stevermeister** [comment]
just removed everything and did with npm install - and now it works, weird..

**Comment by stevermeister** [comment]
ok, now I got something else when try to include the module: 

`AngularSwitcheryModule is not an NgModule`

**Comment by gonzofish** [comment]
Yeah I did too, try doing `AngularSwitcheryModule.forRoot()` on the import

**Comment by stevermeister** [comment]
sorry, my bad, true

**Comment by stevermeister** [comment]
now something new: 
```
ERROR in Error encountered resolving symbol values statically. Calling function 'AngularSwitcheryMo
dule', function calls are not supported. Consider replacing the function or lambda with a reference
 to an exported function, resolving symbol AppModule in /Users/stevermeister/workspace/research/swt
tt/src/app/app.module.ts, resolving symbol AppModule in /Users/stevermeister/workspace/research/swt
tt/src/app/app.module.ts
```

**Comment by gonzofish** [comment]
Weird, I didnt get that. Can I see your `app.module.ts`?

**Comment by stevermeister** [comment]
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AngularSwitcheryModule } from 'angular-switchery';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AngularSwitcheryModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by stevermeister** [comment]
and the most weird thing: 
when I remove line  
    AngularSwitcheryModule.forRoot()
it works
and when I return it back (without stoping `ng serve`) is works!!!!

BUT when I stop `ng serve` and try to run it again - same error

**Comment by gonzofish** [comment]
Interesting...still looking into it

**Comment by gonzofish** [comment]
I'm not sure if this is looking like something the library is doing wrong...

[This issue against the CLI](https://github.com/angular/angular-cli/issues/4956) has devs complaining of the same problem.

**Comment by stevermeister** [comment]
Yes, I also find this thread.
Is there a way to reproduce it without publishing? Basically to run compiled version

**Comment by gonzofish** [comment]
Further investigation led to [this answer by @trekhleb](https://github.com/angular/angular-cli/issues/4647#issuecomment-305967234) which led to [this answer by @SebastianSchenk](https://github.com/angular/angular-cli/issues/3854#issuecomment-274344771)

So I'm not sure _what_ to think...

**Comment by gonzofish** [comment]
So...that error doesn't have a big  effect on running `ng serve` after the initial pass.

Basically, as you said, @stevermeister, if you just save a file for a second time, it'll recompile no problem...this is a really odd problem.

**Comment by gonzofish** [comment]
Quick question, @stevermeister, what OS are you using?

**Comment by stevermeister** [comment]
macOS Sierra

all information about env is provided here - https://github.com/angular/angular-cli/issues/6961

**Comment by gonzofish** [comment]
Well there goes that theory 😢 

Still trying to parse it out...

**Comment by gonzofish** [comment]
Just a "update":

1. I've seen answers from Angular team members saying to others that the metadata isn't being provided or its bad--but from any comparison I do (such as to the Angular Material outputs), everything looks correct.
2. I'm really down in the weeds on the CLI trying to figure this out, I'm looking at the spot where the compiler tries to gather info about our module.
3. This feels a bit insane to be doing.

**Comment by gonzofish** [comment]
I may have figured it out! I think its two-fold:

1. The `types` attribute in `package.json` should be `typings`
2. The value for that attribute should be `./[your package].d.ts` not `./index.d.ts`

So (and you can do this from within your Angular CLI app), modify the `package.json` of your library so that the line:

```json
  "types": "./index.d.ts",
```

becomes:

```json
  "typings": "./angular-switchery.d.ts",
```

And let me know if that fixes anything...

**Comment by gonzofish** [comment]
I published [my test library for Angular librarian with the changes](https://github.com/gonzofish/angular-librarian-test) and it seems to be working.

It also makes it so you don't _have to_ do `.forRoot()`, unless you need to.

**Comment by gonzofish** [comment]
@stevermeister, I'll leave this to you to close. You can do so by updating to the latest version, if need be.

[Link to latest release](https://github.com/gonzofish/angular-librarian/releases/tag/1.0.0-beta.8)

**Comment by stevermeister** [comment]
@gonzofish 
it works!
thank you very much! 
sorry for delay, did not have time to check and update the app.

**Comment by gonzofish** [comment]
Excellent! I'll merge it in when I finish up the testing branch
