### ISSUE TITLE
Scaffold for Examples folder

### ISSUE THREAD

**Issue by gonzofish** [gonzofish/angular-librarian#54]
Allow usage of an `--examples` or `-x` flag so users can add a component/service/etc. to their `examples` directory.

**Comment by gonzofish** [comment]
fd2138c, eeee850, 1e08f58, and 7f0899d close this!

**Comment by x1c0** [comment]
great stuff, thank you, I'll give it a try and then let you know ;)

**Comment by gonzofish** [comment]
It'll be in the next release, beta.10 (sometime this week).
