### ISSUE TITLE
Build fails but does not leave with error

### ISSUE THREAD

**Issue by tommueller** [gonzofish/angular-librarian#61]
I wrote this here #59 already, but I think it will be overseen:

A second issue is, that the `npm run g build` fails, but the CI does not break, but runs through and reports to be successful. Is there maybe a process.exit(1); missing somewhere?

**Comment by gonzofish** [comment]
I've added some code that may help with the false positives you're experiencing, but I cannot be sure

**Comment by tommueller** [comment]
Still having this issue, but I think it is more a gitlab-ci / npm problem, so I will close this.

**Comment by tommueller** [comment]
I was able to fix the error by changing my command from `npm run g test` to `npm test`.

**Comment by gonzofish** [comment]
Ahhhh, good to know! Thanks, that makes perfect sense.
