### ISSUE TITLE
[Migration] rollup-plugin-node-resolve is missing

### ISSUE THREAD

**Issue by tommueller** [gonzofish/angular-librarian#68]
After running `ngl upgrade` from the scoped-branch I get an error running `ngl build` (`ngl serve` works fine!). after running `npm install --save rollup-plugin-node-resolve` the issue is solved.

**Comment by gonzofish** [comment]
Yeah, in the migration guide, I'll add that running `npm install` & `npm update` after is a good idea. I'll also update the `upgrade` script to run those methods in the future

See #71
