### ISSUE TITLE
[Migration] dahToCamel is not a function

### ISSUE THREAD

**Issue by tommueller** [gonzofish/angular-librarian#69]
sadly I get another bug during the upgrade to the latest release ... after fixing #68 the build breaks now during the "rollup-stage". maybe another rollup-dependency that's missing?

> Generating bundles via rollup
> > Build failed
>
> TypeError: librarianUtils.dashToCamel is not a function
>     at doRollup (/home/tom/workspace_angular/ng-core/tasks/rollup.js:28:36)
    at rollupBundles (/home/tom/workspace_angular/ng-core/tasks/build.js:51:29)
    at /home/tom/workspace_angular/ng-core/tasks/build.js:26:16

**Comment by tommueller** [comment]
Sorry: https://github.com/gonzofish/angular-librarian/blob/master/MIGRATION.md

**Comment by gonzofish** [comment]
Yeah, I blew it on that one. Sorry about that...thought I had tested all functionality.
