### ISSUE TITLE
Rollup Configuration

### ISSUE THREAD

**Issue by litzebauer** [gonzofish/angular-librarian#72]
Is it possible to handle Rollup external and globals better in the config?  Explicitly having to call out each external dependency is cumbersome.  Could the script dynamically read from package.json dependencies? Or is there a different way to handle it in Rollup?

**Comment by gonzofish** [comment]
As far as I know, there's really not an easier way, that I know of, to do this. If you look around at other projects, you'll see all of the libraries doing something similar; for example, here's [the Material team explicitly listing their globals](https://github.com/angular/material2/blob/4168fb39db770c977bb2bf36336de6b05d38ef9f/tools/package-tools/rollup-globals.ts#L16) and [then using them to generate their externals](https://github.com/angular/material2/blob/4168fb39db770c977bb2bf36336de6b05d38ef9f/tools/package-tools/rollup-helpers.ts#L41).

I'd like to do something similar to this in [the rollup script](https://github.com/gonzofish/angular-librarian/blob/master/commands/initial/templates/tasks/rollup.js#L115), but I'm not sure if the approach will screw anything up.

It is cumbersome, I agree. But I'm not sure that there's a less cumbersome answer at the moment...

**Comment by litzebauer** [comment]
Hmm, I can see this becoming a problem for people not as well versed in
rollup working on libraries and forgetting to modify that config.

**Comment by gonzofish** [comment]
I get what you're saying and I can add some support docs for helping mitigate common issues. But it really is a necessary part of the build process.

**Comment by litzebauer** [comment]
Maybe a postinstall hook that outputs a warning to update the rollup config
if you are adding a 3rd party dependency.

**Comment by gonzofish** [comment]
Not a bad idea...PR 😄?

**Comment by litzebauer** [comment]
sure

**Comment by gonzofish** [comment]
I updated the list with the huge list of defaults from [ng-packagr](https://github.com/dherges/ng-packagr) via 95eb2bf
