### ISSUE TITLE
Librarian reports false unused module

### ISSUE THREAD

**Issue by tommueller** [gonzofish/angular-librarian#84]
Building my library with angular 5 leads to a warning (maybe this could actually be in yellow, instead of red?) letting me now `'MatSelect' is imported from external module '@angular/material' but never used`, which is not true, I do use this module in one of my components!

```typescript
import { Component, ViewChild } from '@angular/core';
import { MatOption, MatSelect } from '@angular/material';

@Component({
  selector: 'dropdown',
  templateUrl: './dropdown.component.html',
  styleUrls: ['./dropdown.component.scss']
})
export class DropdownComponent {
  [...]

  @ViewChild('select')
  select: MatSelect;

  [...]
}

**Comment by gonzofish** [comment]
You're just using `MatSelect` as a type so, unless you instantiate it elsewhere in `DropdownComponent`, in the compiled code, there is no usage of `MatSelect`.

**Comment by tommueller** [comment]
Well I use it as a component as part of the template ... but this is just a warning, right? I can just ignore it I guess.

**Comment by gonzofish** [comment]
@tommueller I don't believe that using it as type information is enough for it to be considered "used" but that's more of a TypeScript/TSLint issue than Librarian
