### ISSUE TITLE
Upgrading to rollup 0.52.1

### ISSUE THREAD

**Issue by WouterSpaak** [gonzofish/angular-librarian#86]
Angular Librarian currently does not support rollup 0.48+, which is a shame because it has many tree shaking improvements.

I got this working on an internal module of ours. I will file a pull request to upgade Angular Librarian to rollup 0.52.1 in a few hours when I test it on a brand new project. Most of the changes have to do with this document: https://gist.github.com/Rich-Harris/d472c50732dab03efeb37472b08a3f32.

**Comment by gonzofish** [comment]
As I said in the PR, thanks for this PR. Really is a big help and I think the last item before doing v1.0.0

**Comment by WouterSpaak** [comment]
You're quite welcome. We've had a lot of success with Librarian so I'm happy to help! Looking forward to 1.0.0!
