### ISSUE TITLE
[Migration] Rollup bundling fails with: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by tommueller** [gonzofish/angular-librarian#89]
As I mentioned here I ran into another bug after fixing the node-version problem https://github.com/gonzofish/angular-librarian/issues/88#issuecomment-356261787

The build fails now when rollup is executed with:

```
Generating bundles via rollup
[Librarian]: > Build failed

TypeError: Cannot read property 'slice' of undefined
    at startsWith (/home/tom/workspace-angular/ng-core/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:612:13)
    at resolveId (/home/tom/workspace-angular/ng-core/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:653:23)
    at Object.options (/home/tom/workspace-angular/ng-core/node_modules/rollup-plugin-commonjs/dist/rollup-plugin-commonjs.cjs.js:711:27)
    at Bundle$$1.options.plugins.reduce (/home/tom/workspace-angular/ng-core/node_modules/rollup/dist/rollup.js:17905:42)
    at Array.reduce (<anonymous>)
    at new Bundle$$1 (/home/tom/workspace-angular/ng-core/node_modules/rollup/dist/rollup.js:17904:26)
    at Object.rollup (/home/tom/workspace-angular/ng-core/node_modules/rollup/dist/rollup.js:18720:18)
    at bundles.map.config (/home/tom/workspace-angular/ng-core/tasks/rollup.js:73:16)
    at Array.map (<anonymous>)
    at doRollup (/home/tom/workspace-angular/ng-core/tasks/rollup.js:72:7)
```

**Comment by gonzofish** [comment]
On line 73 `rollup.rollup(config)` is called--what does `config` look like when you run build?

**Comment by tommueller** [comment]
Ok, I fixed the error accidentally by changing the code to log the config ... adding curly braces around the `rollup.rollup(config)`-call fixed it ...

```javascript
    const bundles = [
        fesm2015Config,
        fesm5Config,
        minUmdConfig,
        umdConfig
    ].map((config) => {
            rollup.rollup(config).then((bundle) =>
                bundle.write(config)
            )
        }
    );
```

Now I only get some warnings:
```
Copying `src` files into `build`
> Complete
Inlining resources
> Complete
Compiling code
> Complete
Copying typings + metadata to `dist`
> Complete
Generating bundles via rollup
> Complete
Copying package files to `dist`
(node:6807) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not resolve entry (/home/tom/workspace-angular/ng-core/out-tsc/lib-es2015/ng-core.js)
(node:6807) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6807) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Could not resolve entry (/home/tom/workspace-angular/ng-core/out-tsc/lib-es5/ng-core.js)
(node:6807) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Could not resolve entry (/home/tom/workspace-angular/ng-core/out-tsc/lib-es5/ng-core.js)
(node:6807) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Could not resolve entry (/home/tom/workspace-angular/ng-core/out-tsc/lib-es5/ng-core.js)
> Complete
```

**Comment by tommueller** [comment]
I tested more today and also upgraded the project to Angular 5.2.0 and now the export works with my mentioned changes ... I think the it works regardless of the Angular update, as I did not publish the library correctly, but here is my current state in more detail:

- I cannot get this working with your release oob
- Using the upgraded rollup version and changed paths I can compile and use the library
- the fix for "main"-entry in package.json is not necessary anymore and the imported lib works fine (I published the package incorrectly, I was too tired and frustrated apparently last Thursday evening ...)

So I hope this fixes the problems, I will test now if it also works without the Angular upgrade and publish a PR if so.

Best!
Tom

**Comment by tommueller** [comment]
Ok, I give up ... After some more work on the project the build failed again and I had to reset the paths of `es5Dir` and `es2015Dir` back to your version ... Right now I use the latest rollup version and it works with your code. I have no idea what I changed though ...

**Comment by SirDarquan** [comment]
I ran into this problem a couple days ago as well. To see if there was a problem with ngl, I created a brand new empty library and performed a build. Of course it worked perfectly which led me to wonder what was different about my real library. To make a long story short, the package-lock.json was keeping specific versions of packages that ngl relied on at pre-update versions. It's designed to do this if the direct dependencies don't change. So the easiest solution was to just delete my package-lock.json file and do an npm install. everything updated and the build began to work.

I'm sure that there's a more 'official' way to tell npm to update indirect dependencies but I didn't really feel like searching to understand what it was. Maybe the migration docs should make a mention of this as a possible fix if it works for most projects, that is.

**Comment by gonzofish** [comment]
Thank you so much for figuring this out! I’ll see if I can investigate and
give an official solution. In the meantime I’ll put a note in the migration
document.

**Comment by gonzofish** [comment]
Btw, I've added a note to the [MIGRATION.md](https://github.com/gonzofish/angular-librarian/blob/master/MIGRATION.md) file with @SirDarquan's mitigation

**Comment by gonzofish** [comment]
Closing this with the MIGRATION.md addition
