### ISSUE TITLE
git workflow for libraries

### ISSUE THREAD

**Issue by ovione** [gonzofish/angular-librarian#93]
hi 

I was wondering what is the git workflow when creating libraries ?

If I have a library that uses angular 4.x and the same library that uses angular 5.x

should they be in the same repo in different branches or in different repos ?
I would like to have opinions about this.

For application development I use git workflow http://datasift.github.io/gitflow/IntroducingGitFlow.html..
Is there similar articles when developing libraries ?

thanks

**Comment by gonzofish** [comment]
I'm sure it's frustrating that there isn't clear guidance on how such things should be done, but this is really a Librarian-specific (or even Angular-specific) question, so I'm going to close it. Sorry.
